namespace MK.Logic.Runtime.CardEffects
{
    /// <summary>
    /// 行動牌效果枚舉。僅覆蓋示範用的數張牌。
    /// </summary>
    public enum ActionEffectId
    {
        Move2,
        Move4,
        Heal1,
        Heal2,
        Influence2,
        Influence4,
        HealOrDraw1,
        HealOrDraw2,
        GainManaBWR,
        ConcentrationBoost,
        WildHarvestBase,
        WildHarvestEnhanced,
        EarthStrengthBase,
        EarthStrengthEnhanced,
        RefreshingBase,
        RefreshingEnhanced,
        WillFocusBase,
        WillFocusBoost,
        RangedAttack3,
        ManaDrawBase,
        ManaDrawEnhanced,

        QuickReflexesBase,
        QuickReflexesEnhanced,
        ThrowingAxeBase,
        ThrowingAxeEnhanced,
        NobleMannersBase,
        NobleMannersEnhanced,
        ManaPullBase,
        ManaPullEnhanced,
        CrystallizeBase,
        CrystallizeEnhanced,
        DeterminationBase,
        DeterminationEnhanced,
        MoveBoostBase,
        MoveBoostEnhanced,
        DruidicPathsBase,
        DruidicPathsEnhanced,
        JoyfulManaBase,
        JoyfulManaEnhanced
        ,IcyShellBase
        ,IcyShellEnhanced
        ,FuryBase
        ,FuryEnhanced
        ,ThreatenBase
        ,ThreatenEnhanced
        ,ImprovisationBase
        ,ImprovisationEnhanced
        ,VersatileBattleBase
        ,VersatileBattleEnhanced
        ,BattleRageBase
        ,BattleRageEnhanced
        ,IntimidateBase
        ,IntimidateEnhanced
        ,UnknownBase
        ,UnknownEnhanced
        ,FireBoltBase
        ,FireBoltEnhanced
        ,IceBoltBase
        ,IceBoltEnhanced
        ,SwiftBoltBase
        ,SwiftBoltEnhanced
        ,ShatterBoltBase
        ,ShatterBoltEnhanced
        ,BloodRageBase
        ,BloodRageEnhanced
        ,IceShieldBase
        ,IceShieldEnhanced
        ,AgilityBase
        ,AgilityEnhanced
        ,RefreshingWalkBase
        ,RefreshingWalkEnhanced
        ,CoercionBase
        ,CoercionEnhanced,
        FrostBridgeBase,
        FrostBridgeEnhanced,
        WindSongBase,
        WindSongEnhanced,
        PathFindingBase,
        PathFindingEnhanced,
        BloodRitualBase,
        BloodRitualEnhanced,
        PureMagicBase,
        PureMagicEnhanced,
        DeedsOfGloryBase,
        DeedsOfGloryEnhanced,
        RegenerationBase,
        RegenerationEnhanced,
        ChargeBase,
        ChargeEnhanced,
        SteadyTempoBase,
        SteadyTempoEnhanced,
        DiplomacyBase,
        DiplomacyEnhanced,
        CallForHelpBase,
        CallForHelpEnhanced,
        DecomposeBase,
        DecomposeEnhanced,
        CrystalMasteryBase,
        CrystalMasteryEnhanced,
        ManaStormBase,
        ManaStormEnhanced,
        AmbushBase,
        AmbushEnhanced,
        OverloadBase,
        OverloadEnhanced,
        MagicTalentBase,
        MagicTalentEnhanced,
        LearningBase,
        LearningEnhanced,
        PracticeBase,
        PracticeEnhanced,
        CounterStrikeBase,
        CounterStrikeEnhanced,
        RitualAttackBase,
        RitualAttackEnhanced,
        AncientBloodlineBase,
        AncientBloodlineEnhanced,
        ShieldBashBase,
        ShieldBashEnhanced,
        TimeBendingBase,
        TimeBendingEnhanced,
        SpellForgeBase,
        SpellForgeEnhanced,
        KnightlySpiritBase,
        KnightlySpiritEnhanced,
        TranquilTimeBase,
        TranquilTimeEnhanced,
        OutmaneuverBase,
        OutmaneuverEnhanced,
        PerseveranceBase,
        PerseveranceEnhanced,
        NatureForceBase,
        NatureForceEnhanced,
        MountainLoreBase,
        MountainLoreEnhanced,
        ManaPowerBase,
        ManaPowerEnhanced,
        ExplosiveBoltsBase,
        ExplosiveBoltsEnhanced,
        BloodSurgeBase,
        BloodSurgeEnhanced,
        ColdStareBase,
        ColdStareEnhanced,
        // ─── 法術牌編號000～011 ─────────────────────
        EnergyFlowBase,
        EnergyStealEnhanced,
        CureBase,
        InfectEnhanced,
        MeditationBase,
        TranceEnhanced,
        EarthTremorBase,
        EarthQuakeEnhanced,
        TunnelTravelBase,
        TunnelAttackEnhanced,
        RestoreBase,
        RebirthEnhanced,
        ManaMeltdownBase,
        ManaRadiationEnhanced,
        DemolishBase,
        DisintegrateEnhanced,
        BurningShieldBase,
        BlastShieldEnhanced,
        FireballBase,
        FirestormEnhanced,
        FlameWallBase,
        FlameWaveEnhanced,
        SacrificeBase,
        SacrificeEnhanced,
        // ─── 法術牌編號012～023 ─────────────────────
        ManaClaimBase,
        ManaCurseEnhanced,
        FreezeBase,
        DeadlyFreezeEnhanced,
        MistFormBase,
        MistShroudEnhanced,
        BlizzardBase,
        BlizzardStormEnhanced,
        WarpSpaceBase,
        WarpTimeEnhanced,
        ManaBoltBase,
        ManaThunderEnhanced,
        MindReadBase,
        MindStealEnhanced,
        ExposureBase,
        MassExposureEnhanced,
        BattleSummonsBase,
        HonorSummonsEnhanced,
        CharmBase,
        PossessEnhanced,
        WhirlwindBase,
        HurricaneEnhanced,
        WindWingsBase,
        NightWingsEnhanced,

        // ─── 物品牌效果編號000～003 ─────────────────────
        HonorBannerAssign,
        HonorBannerOnce,
        FearBannerAssign,
        FearBannerOnce,
        FortitudeBannerAssign,
        FortitudeBannerOnce,
        CourageBannerAssign,
        CourageBannerOnce,

        // ─── 物品牌效果編號004～008 ─────────────────────
        RubyRingAssign,
        RubyRingOnce,
        SapphireRingAssign,
        SapphireRingOnce,
        DiamondRingAssign,
        DiamondRingOnce,
        EmeraldRingAssign,
        EmeraldRingOnce,
        JusticeSwordAssign,
        JusticeSwordOnce,

        // ─── 物品牌效果編號009～014 ─────────────────────
        WrathHornAssign,
        WrathHornOnce,
        GoldPouchAssign,
        GoldPouchOnce,
        GemBagAssign,
        GemBagOnce,
        HolyGrailAssign,
        HolyGrailOnce,
        WisdomBookAssign,
        WisdomBookOnce,
        SunAmuletAssign,
        SunAmuletOnce,

        // ─── 物品牌效果編號015～020 ─────────────────────
        DarkAmuletAssign,
        DarkAmuletOnce,
        StarBowAssign,
        StarBowOnce,
        CommandBannerAssign,
        CommandBannerOnce,
        ToughBannerAssign,
        ToughBannerOnce,
        SoulHarvesterAssign,
        SoulHarvesterOnce,
        NecroShieldAssign,
        NecroShieldOnce,

        // ─── 物品牌效果編號021～024 ─────────────────────
        DruidStaffAssign,
        DruidStaffOnce,
        HeadbandAssign,
        HeadbandOnce,
        SpellTomeAssign,
        SpellTomeOnce,
        MysticBoxAssign,
        MysticBoxOnce,
        InstinctBase,
        InstinctEnhanced
    }
}
