using System.Collections.Generic;
using MK.Logic.Core;

namespace MK.Logic.Runtime.CardEffects
{
    /// <summary>
    /// 根據效果枚舉提供對應的實例。簡化為靜態字典。 
    /// </summary>
    public static class CardEffectFactory
    {
        private static readonly Dictionary<ActionEffectId, ICardEffect> _effects = new()
        {
            { ActionEffectId.Move2, new MoveEffect(2) },
            { ActionEffectId.Move4, new MoveEffect(4) },
            { ActionEffectId.Heal1, new HealEffect(1) },
            { ActionEffectId.Heal2, new HealEffect(2) },
            { ActionEffectId.Influence2, new InfluenceEffect(2) },
            { ActionEffectId.Influence4, new InfluenceEffect(4) },
            { ActionEffectId.HealOrDraw1, new HealOrDrawEffect(1,1) },
            { ActionEffectId.HealOrDraw2, new HealOrDrawEffect(2,2) },
            { ActionEffectId.GainManaBWR, new ManaGainEffect(false, ManaColor.Blue, ManaColor.White, ManaColor.Red) },
            { ActionEffectId.ConcentrationBoost, new BoostNextCardEffect(2) },
            { ActionEffectId.WildHarvestBase, new WildHarvestEffect(2,1) },
            { ActionEffectId.WildHarvestEnhanced, new WildHarvestEffect(4,-1) },
            { ActionEffectId.EarthStrengthBase, new EarthStrengthEffect(2,1,false) },
            { ActionEffectId.EarthStrengthEnhanced, new EarthStrengthEffect(4,2,true) },
            { ActionEffectId.RefreshingBase, new RefreshingEffect(1,1,false,2) },
            { ActionEffectId.RefreshingEnhanced, new RefreshingEffect(2,2,true,3) },
            { ActionEffectId.WillFocusBase, new ManaGainEffect(false, ManaColor.Blue, ManaColor.White, ManaColor.Red) },
            { ActionEffectId.WillFocusBoost, new BoostNextCardEffect(3) },
            { ActionEffectId.RangedAttack3, new RangedAttackEffect(3) },
            { ActionEffectId.ManaDrawBase, new ManaDrawEffect(false) },
            { ActionEffectId.ManaDrawEnhanced, new ManaDrawEffect(true) },

            { ActionEffectId.QuickReflexesBase, new QuickReflexesEffect(2,1,1) },
            { ActionEffectId.QuickReflexesEnhanced, new QuickReflexesEffect(4,3,2) },
            { ActionEffectId.ThrowingAxeBase, new ThrowingAxeEffect(false) },
            { ActionEffectId.ThrowingAxeEnhanced, new ThrowingAxeEffect(true) },
            { ActionEffectId.NobleMannersBase, new NobleMannersEffect(2,false) },
            { ActionEffectId.NobleMannersEnhanced, new NobleMannersEffect(4,true) },
            { ActionEffectId.ManaPullBase, new ManaPullEffect(false) },
            { ActionEffectId.ManaPullEnhanced, new ManaPullEffect(true) },
            { ActionEffectId.CrystallizeBase, new CrystallizeEffect(false) },
            { ActionEffectId.CrystallizeEnhanced, new CrystallizeEffect(true) },
            { ActionEffectId.DeterminationBase, new DeterminationEffect(false) },
            { ActionEffectId.DeterminationEnhanced, new DeterminationEffect(true) },
            { ActionEffectId.MoveBoostBase, new MoveBoostEffect(2,false) },
            { ActionEffectId.MoveBoostEnhanced, new MoveBoostEffect(4,true) },
            { ActionEffectId.DruidicPathsBase, new DruidicPathsEffect(2,false) },
            { ActionEffectId.DruidicPathsEnhanced, new DruidicPathsEffect(4,true) },
            { ActionEffectId.JoyfulManaBase, new JoyfulManaEffect(false) },
            { ActionEffectId.JoyfulManaEnhanced, new JoyfulManaEffect(true) },

            { ActionEffectId.IcyShellBase, new IcyShellEffect(false) },
            { ActionEffectId.IcyShellEnhanced, new IcyShellEffect(true) },
            { ActionEffectId.FuryBase, new FuryEffect(false) },
            { ActionEffectId.FuryEnhanced, new FuryEffect(true) },
            { ActionEffectId.ThreatenBase, new ThreatenEffect(false) },
            { ActionEffectId.ThreatenEnhanced, new ThreatenEffect(true) },
            { ActionEffectId.ImprovisationBase, new ImprovisationEffect(false) },
            { ActionEffectId.ImprovisationEnhanced, new ImprovisationEffect(true) },
            { ActionEffectId.VersatileBattleBase, new VersatileBattleEffect(false) },
            { ActionEffectId.VersatileBattleEnhanced, new VersatileBattleEffect(true) },
            { ActionEffectId.BattleRageBase, new BattleRageEffect(false) },
            { ActionEffectId.BattleRageEnhanced, new BattleRageEffect(true) },
            { ActionEffectId.IntimidateBase, new IntimidateEffect(false) },
            { ActionEffectId.IntimidateEnhanced, new IntimidateEffect(true) },
            { ActionEffectId.UnknownBase, new UnknownEffect() },
            { ActionEffectId.UnknownEnhanced, new UnknownEffect() },

            { ActionEffectId.FireBoltBase, new ManaGainEffect(true, ManaColor.Red) },
            { ActionEffectId.FireBoltEnhanced, new RangedAttackEffect(3) },
            { ActionEffectId.IceBoltBase, new ManaGainEffect(true, ManaColor.Blue) },
            { ActionEffectId.IceBoltEnhanced, new RangedAttackEffect(3) },
            { ActionEffectId.SwiftBoltBase, new ManaGainEffect(true, ManaColor.White) },
            { ActionEffectId.SwiftBoltEnhanced, new RangedAttackEffect(4) },
            { ActionEffectId.ShatterBoltBase, new ManaGainEffect(true, ManaColor.Green) },
            { ActionEffectId.ShatterBoltEnhanced, new RangedAttackEffect(3) },
            { ActionEffectId.BloodRageBase, new BloodRageEffect(false) },
            { ActionEffectId.BloodRageEnhanced, new BloodRageEffect(true) },
            { ActionEffectId.IceShieldBase, new IceShieldEffect(false) },
            { ActionEffectId.IceShieldEnhanced, new IceShieldEffect(true) },
            { ActionEffectId.AgilityBase, new AgilityEffect(false) },
            { ActionEffectId.AgilityEnhanced, new AgilityEffect(true) },
            { ActionEffectId.RefreshingWalkBase, new RefreshingWalkEffect(false) },
            { ActionEffectId.RefreshingWalkEnhanced, new RefreshingWalkEffect(true) },
            { ActionEffectId.CoercionBase, new CoercionEffect(false) },
            { ActionEffectId.CoercionEnhanced, new CoercionEffect(true) },
            { ActionEffectId.FrostBridgeBase, new FrostBridgeEffect(false) },
            { ActionEffectId.FrostBridgeEnhanced, new FrostBridgeEffect(true) },
            { ActionEffectId.WindSongBase, new WindSongEffect(false) },
            { ActionEffectId.WindSongEnhanced, new WindSongEffect(true) },
            { ActionEffectId.PathFindingBase, new PathFindingEffect(false) },
            { ActionEffectId.PathFindingEnhanced, new PathFindingEffect(true) },
            { ActionEffectId.BloodRitualBase, new BloodRitualEffect(false) },
            { ActionEffectId.BloodRitualEnhanced, new BloodRitualEffect(true) },
            { ActionEffectId.PureMagicBase, new PureMagicEffect(false) },
            { ActionEffectId.PureMagicEnhanced, new PureMagicEffect(true) },
            { ActionEffectId.DeedsOfGloryBase, new DeedsOfGloryEffect(false) },
            { ActionEffectId.DeedsOfGloryEnhanced, new DeedsOfGloryEffect(true) },
            { ActionEffectId.RegenerationBase, new RegenerationEffect(false) },
            { ActionEffectId.RegenerationEnhanced, new RegenerationEffect(true) },
            { ActionEffectId.ChargeBase, new ChargeEffect(false) },
            { ActionEffectId.ChargeEnhanced, new ChargeEffect(true) },

            { ActionEffectId.SteadyTempoBase, new SteadyTempoEffect(false) },
            { ActionEffectId.SteadyTempoEnhanced, new SteadyTempoEffect(true) },
            { ActionEffectId.DiplomacyBase, new DiplomacyEffect(false) },
            { ActionEffectId.DiplomacyEnhanced, new DiplomacyEffect(true) },
            { ActionEffectId.CallForHelpBase, new CallForHelpEffect(false) },
            { ActionEffectId.CallForHelpEnhanced, new CallForHelpEffect(true) },
            { ActionEffectId.DecomposeBase, new DecomposeEffect(false) },
            { ActionEffectId.DecomposeEnhanced, new DecomposeEffect(true) },
            { ActionEffectId.CrystalMasteryBase, new CrystalMasteryEffect(false) },
            { ActionEffectId.CrystalMasteryEnhanced, new CrystalMasteryEffect(true) },
            { ActionEffectId.ManaStormBase, new ManaStormEffect(false) },
            { ActionEffectId.ManaStormEnhanced, new ManaStormEffect(true) },
            { ActionEffectId.AmbushBase, new AmbushEffect(false) },
            { ActionEffectId.AmbushEnhanced, new AmbushEffect(true) },
            { ActionEffectId.OverloadBase, new OverloadEffect(false) },
            { ActionEffectId.OverloadEnhanced, new OverloadEffect(true) },

            { ActionEffectId.MagicTalentBase, new MagicTalentEffect(false) },
            { ActionEffectId.MagicTalentEnhanced, new MagicTalentEffect(true) },
            { ActionEffectId.LearningBase, new LearningEffect(false) },
            { ActionEffectId.LearningEnhanced, new LearningEffect(true) },
            { ActionEffectId.PracticeBase, new PracticeEffect(false) },
            { ActionEffectId.PracticeEnhanced, new PracticeEffect(true) },
            { ActionEffectId.CounterStrikeBase, new CounterStrikeEffect(false) },
            { ActionEffectId.CounterStrikeEnhanced, new CounterStrikeEffect(true) },
            { ActionEffectId.RitualAttackBase, new RitualAttackEffect(false) },
            { ActionEffectId.RitualAttackEnhanced, new RitualAttackEffect(true) },
            { ActionEffectId.AncientBloodlineBase, new AncientBloodlineEffect(false) },
            { ActionEffectId.AncientBloodlineEnhanced, new AncientBloodlineEffect(true) },
            { ActionEffectId.ShieldBashBase, new ShieldBashEffect(false) },
            { ActionEffectId.ShieldBashEnhanced, new ShieldBashEffect(true) },
            { ActionEffectId.TimeBendingBase, new TimeBendingEffect(false) },
            { ActionEffectId.TimeBendingEnhanced, new TimeBendingEffect(true) },
            { ActionEffectId.SpellForgeBase, new SpellForgeEffect(false) },
            { ActionEffectId.SpellForgeEnhanced, new SpellForgeEffect(true) },
            { ActionEffectId.KnightlySpiritBase, new KnightlySpiritEffect(false) },
            { ActionEffectId.KnightlySpiritEnhanced, new KnightlySpiritEffect(true) },

            { ActionEffectId.TranquilTimeBase, new TranquilTimeEffect(false) },
            { ActionEffectId.TranquilTimeEnhanced, new TranquilTimeEffect(true) },
            { ActionEffectId.OutmaneuverBase, new OutmaneuverEffect(false) },
            { ActionEffectId.OutmaneuverEnhanced, new OutmaneuverEffect(true) },
            { ActionEffectId.PerseveranceBase, new PerseveranceEffect(false) },
            { ActionEffectId.PerseveranceEnhanced, new PerseveranceEffect(true) },
            { ActionEffectId.NatureForceBase, new NatureForceEffect(false) },
            { ActionEffectId.NatureForceEnhanced, new NatureForceEffect(true) },
            { ActionEffectId.MountainLoreBase, new MountainLoreEffect(false) },
            { ActionEffectId.MountainLoreEnhanced, new MountainLoreEffect(true) },
            { ActionEffectId.ManaPowerBase, new ManaPowerEffect(false) },
            { ActionEffectId.ManaPowerEnhanced, new ManaPowerEffect(true) },
            { ActionEffectId.ExplosiveBoltsBase, new ExplosiveBoltsEffect(false) },
            { ActionEffectId.ExplosiveBoltsEnhanced, new ExplosiveBoltsEffect(true) },
            { ActionEffectId.BloodSurgeBase, new BloodSurgeEffect(false) },
            { ActionEffectId.BloodSurgeEnhanced, new BloodSurgeEffect(true) },
            { ActionEffectId.ColdStareBase, new ColdStareEffect(false) },
            { ActionEffectId.ColdStareEnhanced, new ColdStareEffect(true) },

            // ─── 法術牌效果 ────────────────────────────────
            { ActionEffectId.EnergyFlowBase, new EnergyFlowEffect(false) },
            { ActionEffectId.EnergyStealEnhanced, new EnergyFlowEffect(true) },
            { ActionEffectId.CureBase, new CureEffect(false) },
            { ActionEffectId.InfectEnhanced, new CureEffect(true) },
            { ActionEffectId.MeditationBase, new MeditationEffect(false) },
            { ActionEffectId.TranceEnhanced, new MeditationEffect(true) },
            { ActionEffectId.EarthTremorBase, new EarthTremorEffect(false) },
            { ActionEffectId.EarthQuakeEnhanced, new EarthTremorEffect(true) },
            { ActionEffectId.TunnelTravelBase, new TunnelTravelEffect(false) },
            { ActionEffectId.TunnelAttackEnhanced, new TunnelTravelEffect(true) },
            { ActionEffectId.RestoreBase, new RestoreEffect(false) },
            { ActionEffectId.RebirthEnhanced, new RestoreEffect(true) },
            { ActionEffectId.ManaMeltdownBase, new ManaMeltdownEffect(false) },
            { ActionEffectId.ManaRadiationEnhanced, new ManaMeltdownEffect(true) },
            { ActionEffectId.DemolishBase, new DemolishEffect(false) },
            { ActionEffectId.DisintegrateEnhanced, new DemolishEffect(true) },
            { ActionEffectId.BurningShieldBase, new BurningShieldEffect(false) },
            { ActionEffectId.BlastShieldEnhanced, new BurningShieldEffect(true) },
            { ActionEffectId.FireballBase, new FireballEffect(false) },
            { ActionEffectId.FirestormEnhanced, new FireballEffect(true) },
            { ActionEffectId.FlameWallBase, new FlameWallEffect(false) },
            { ActionEffectId.FlameWaveEnhanced, new FlameWallEffect(true) },
            { ActionEffectId.SacrificeBase, new SacrificeEffect(false) },
            { ActionEffectId.SacrificeEnhanced, new SacrificeEffect(true) },

            { ActionEffectId.ManaClaimBase, new ManaClaimEffect(false) },
            { ActionEffectId.ManaCurseEnhanced, new ManaClaimEffect(true) },
            { ActionEffectId.FreezeBase, new FreezeEffect(false) },
            { ActionEffectId.DeadlyFreezeEnhanced, new FreezeEffect(true) },
            { ActionEffectId.MistFormBase, new MistFormEffect(false) },
            { ActionEffectId.MistShroudEnhanced, new MistFormEffect(true) },
            { ActionEffectId.BlizzardBase, new BlizzardEffect(false) },
            { ActionEffectId.BlizzardStormEnhanced, new BlizzardEffect(true) },
            { ActionEffectId.WarpSpaceBase, new WarpEffect(false) },
            { ActionEffectId.WarpTimeEnhanced, new WarpEffect(true) },
            { ActionEffectId.ManaBoltBase, new ManaBoltEffect(false) },
            { ActionEffectId.ManaThunderEnhanced, new ManaBoltEffect(true) },
            { ActionEffectId.MindReadBase, new MindReadEffect(false) },
            { ActionEffectId.MindStealEnhanced, new MindReadEffect(true) },
            { ActionEffectId.ExposureBase, new ExposureEffect(false) },
            { ActionEffectId.MassExposureEnhanced, new ExposureEffect(true) },
            { ActionEffectId.BattleSummonsBase, new BattleSummonsEffect(false) },
            { ActionEffectId.HonorSummonsEnhanced, new BattleSummonsEffect(true) },
            { ActionEffectId.CharmBase, new CharmEffect(false) },
            { ActionEffectId.PossessEnhanced, new CharmEffect(true) },
            { ActionEffectId.WhirlwindBase, new WhirlwindEffect(false) },
            { ActionEffectId.HurricaneEnhanced, new WhirlwindEffect(true) },
            { ActionEffectId.WindWingsBase, new WindWingsEffect(false) },
            { ActionEffectId.NightWingsEnhanced, new WindWingsEffect(true) },

            { ActionEffectId.HonorBannerAssign, new HonorBannerEffect(false) },
            { ActionEffectId.HonorBannerOnce, new HonorBannerEffect(true) },
            { ActionEffectId.FearBannerAssign, new FearBannerEffect(false) },
            { ActionEffectId.FearBannerOnce, new FearBannerEffect(true) },
            { ActionEffectId.FortitudeBannerAssign, new FortitudeBannerEffect(false) },
            { ActionEffectId.FortitudeBannerOnce, new FortitudeBannerEffect(true) },
            { ActionEffectId.CourageBannerAssign, new CourageBannerEffect(false) },
            { ActionEffectId.CourageBannerOnce, new CourageBannerEffect(true) },

            { ActionEffectId.RubyRingAssign, new RubyRingEffect(false) },
            { ActionEffectId.RubyRingOnce, new RubyRingEffect(true) },
            { ActionEffectId.SapphireRingAssign, new SapphireRingEffect(false) },
            { ActionEffectId.SapphireRingOnce, new SapphireRingEffect(true) },
            { ActionEffectId.DiamondRingAssign, new DiamondRingEffect(false) },
            { ActionEffectId.DiamondRingOnce, new DiamondRingEffect(true) },
            { ActionEffectId.EmeraldRingAssign, new EmeraldRingEffect(false) },
            { ActionEffectId.EmeraldRingOnce, new EmeraldRingEffect(true) },
            { ActionEffectId.JusticeSwordAssign, new JusticeSwordEffect(false) },
            { ActionEffectId.JusticeSwordOnce, new JusticeSwordEffect(true) },

            { ActionEffectId.WrathHornAssign, new WrathHornEffect(false) },
            { ActionEffectId.WrathHornOnce, new WrathHornEffect(true) },
            { ActionEffectId.GoldPouchAssign, new GoldPouchEffect(false) },
            { ActionEffectId.GoldPouchOnce, new GoldPouchEffect(true) },
            { ActionEffectId.GemBagAssign, new GemBagEffect(false) },
            { ActionEffectId.GemBagOnce, new GemBagEffect(true) },
            { ActionEffectId.HolyGrailAssign, new HolyGrailEffect(false) },
            { ActionEffectId.HolyGrailOnce, new HolyGrailEffect(true) },
            { ActionEffectId.WisdomBookAssign, new WisdomBookEffect(false) },
            { ActionEffectId.WisdomBookOnce, new WisdomBookEffect(true) },
            { ActionEffectId.SunAmuletAssign, new SunAmuletEffect(false) },
            { ActionEffectId.SunAmuletOnce, new SunAmuletEffect(true) },

            { ActionEffectId.DarkAmuletAssign, new DarkAmuletEffect(false) },
            { ActionEffectId.DarkAmuletOnce, new DarkAmuletEffect(true) },
            { ActionEffectId.StarBowAssign, new StarBowEffect(false) },
            { ActionEffectId.StarBowOnce, new StarBowEffect(true) },
            { ActionEffectId.CommandBannerAssign, new CommandBannerEffect(false) },
            { ActionEffectId.CommandBannerOnce, new CommandBannerEffect(true) },
            { ActionEffectId.ToughBannerAssign, new ToughBannerEffect(false) },
            { ActionEffectId.ToughBannerOnce, new ToughBannerEffect(true) },
            { ActionEffectId.SoulHarvesterAssign, new SoulHarvesterEffect(false) },
            { ActionEffectId.SoulHarvesterOnce, new SoulHarvesterEffect(true) },
            { ActionEffectId.NecroShieldAssign, new NecroShieldEffect(false) },
            { ActionEffectId.NecroShieldOnce, new NecroShieldEffect(true) },

            { ActionEffectId.DruidStaffAssign, new DruidStaffEffect(false) },
            { ActionEffectId.DruidStaffOnce, new DruidStaffEffect(true) },
            { ActionEffectId.HeadbandAssign, new HeadbandEffect(false) },
            { ActionEffectId.HeadbandOnce, new HeadbandEffect(true) },
            { ActionEffectId.SpellTomeAssign, new SpellTomeEffect(false) },
            { ActionEffectId.SpellTomeOnce, new SpellTomeEffect(true) },
            { ActionEffectId.MysticBoxAssign, new MysticBoxEffect(false) },
            { ActionEffectId.MysticBoxOnce, new MysticBoxEffect(true) }
        };

        public static ICardEffect Get(ActionEffectId id) => _effects[id];
    }
}
